In [1]:
import pandas as pd

In [2]:
fake = pd.read_csv("dataset/Fake.csv") 
true = pd.read_csv("dataset/True.csv")
print("fake dataset rows and columns = ",fake.shape)
print("\ntrue dataset rows and collumns = ",true.shape)

fake dataset rows and columns =  (23481, 4)

true dataset rows and collumns =  (21417, 4)

In [3]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [4]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [5]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import re
import string

In [7]:
fake_manual_testing = fake.tail(10)
for i in range(23480,23470,-1):
    fake.drop([i],axis = 0, inplace = True)

true_manual_testing = true.tail(10)
for i in range(21416,21406,-1):
    true.drop([i],axis = 0, inplace = True)

fake.shape,true.shape

((23471, 4), (21407, 4))

In [8]:
fake_manual_testing['class'] = 0
true_manual_testing ['class'] = 1

/tmp/ipykernel_23501/4109221998.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fake_manual_testing['class'] = 0
/tmp/ipykernel_23501/4109221998.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  true_manual_testing ['class'] = 1

In [9]:
fake_manual_testing.head(10)

,title,text,subject,date,class
23471,Seven Iranians freed in the prisoner swap have...,"21st Century Wire says This week, the historic...",Middle-east,"January 20, 2016",0
23472,#Hashtag Hell & The Fake Left,By Dady Chery and Gilbert MercierAll writers ...,Middle-east,"January 19, 2016",0
23473,Astroturfing: Journalist Reveals Brainwashing ...,Vic Bishop Waking TimesOur reality is carefull...,Middle-east,"January 19, 2016",0
23474,The New American Century: An Era of Fraud,Paul Craig RobertsIn the last years of the 20t...,Middle-east,"January 19, 2016",0
23475,Hillary Clinton: ‘Israel First’ (and no peace ...,Robert Fantina CounterpunchAlthough the United...,Middle-east,"January 18, 2016",0
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",0
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",0
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",0
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",0
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",0

In [10]:
true_manual_testing.head(10)

,title,text,subject,date,class
21407,"Mata Pires, owner of embattled Brazil builder ...","SAO PAULO (Reuters) - Cesar Mata Pires, the ow...",worldnews,"August 22, 2017",1
21408,"U.S., North Korea clash at U.N. forum over nuc...",GENEVA (Reuters) - North Korea and the United ...,worldnews,"August 22, 2017",1
21409,"U.S., North Korea clash at U.N. arms forum on ...",GENEVA (Reuters) - North Korea and the United ...,worldnews,"August 22, 2017",1
21410,Headless torso could belong to submarine journ...,COPENHAGEN (Reuters) - Danish police said on T...,worldnews,"August 22, 2017",1
21411,North Korea shipments to Syria chemical arms a...,UNITED NATIONS (Reuters) - Two North Korean sh...,worldnews,"August 21, 2017",1
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [11]:
fake['class'] = 0
true['class'] = 1
data_merge = pd.concat([fake,true], axis = 0)
data_merge.head()

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [12]:
data_merge.tail()

,title,text,subject,date,class
21402,Exclusive: Trump's Afghan decision may increas...,ON BOARD A U.S. MILITARY AIRCRAFT (Reuters) - ...,worldnews,"August 22, 2017",1
21403,U.S. puts more pressure on Pakistan to help wi...,WASHINGTON (Reuters) - The United States sugge...,worldnews,"August 21, 2017",1
21404,Exclusive: U.S. to withhold up to $290 million...,WASHINGTON (Reuters) - The United States has d...,worldnews,"August 22, 2017",1
21405,Trump talks tough on Pakistan's 'terrorist' ha...,ISLAMABAD (Reuters) - Outlining a new strategy...,worldnews,"August 22, 2017",1
21406,"U.S., North Korea clash at U.N. forum over nuc...",GENEVA (Reuters) - North Korea and the United ...,worldnews,"August 22, 2017",1

In [13]:
data_merge.columns

Index(['title', 'text', 'subject', 'date', 'class'], dtype='object')

In [14]:
data_merge.isnull().sum()

title      0
text       0
subject    0
date       0
class      0
dtype: int64

In [15]:
data = data_merge.drop(['title','subject','date'],axis = 1)

In [16]:
data = data.sample(frac= 1)

In [17]:
data.head()

                                                    text  class
14862  SYDNEY (Reuters) - The citizenship crisis engu...      1
4527   With this presidential election being as absol...      0
18662  BEIJING (Reuters) - The southwestern Chinese m...      1
15084  So much for the media s attempt to make Donald...      0
18787  Ted Nugent is all smiles, as he s pictured wit...      0

In [18]:
data.reset_index(inplace=True)
data

       index                                               text  class
0      14862  SYDNEY (Reuters) - The citizenship crisis engu...      1
1       4527  With this presidential election being as absol...      0
2      18662  BEIJING (Reuters) - The southwestern Chinese m...      1
3      15084  So much for the media s attempt to make Donald...      0
4      18787  Ted Nugent is all smiles, as he s pictured wit...      0
...      ...                                                ...    ...
44873   1056  Alleged President Donald Trump has been on the...      0
44874  12158  Outspoken conservative Tomi Lahren makes some ...      0
44875  13200  BELFAST (Reuters) - The leader of the Northern...      1
44876   6919  SIMI VALLEY, California (Reuters) - Often fier...      1
44877  17692  The move by a Twitter employee last week to ba...      0

[44878 rows x 3 columns]

In [19]:
data.drop(['index'],axis=1,inplace= True)
data

                                                    text  class
0      SYDNEY (Reuters) - The citizenship crisis engu...      1
1      With this presidential election being as absol...      0
2      BEIJING (Reuters) - The southwestern Chinese m...      1
3      So much for the media s attempt to make Donald...      0
4      Ted Nugent is all smiles, as he s pictured wit...      0
...                                                  ...    ...
44873  Alleged President Donald Trump has been on the...      0
44874  Outspoken conservative Tomi Lahren makes some ...      0
44875  BELFAST (Reuters) - The leader of the Northern...      1
44876  SIMI VALLEY, California (Reuters) - Often fier...      1
44877  The move by a Twitter employee last week to ba...      0

[44878 rows x 2 columns]

In [20]:
data.columns

Index(['text', 'class'], dtype='object')

In [21]:
def wordopt(text):
    text = text.lower()
    text = re.sub('\[_*?\]','', text)
    text = re.sub("\\W"," ",text)
    text = re.sub('https?://\S+|www\.\S+','',text)
    text = re.sub('<.*?>+','',text)
    text = re.sub('[%s]'% re.escape(string.punctuation),'',text)
    text = re.sub('\n','',text)
    text = re.sub('\w*\d\w*','',text)
    return text

<>:3: SyntaxWarning: invalid escape sequence '\['
<>:5: SyntaxWarning: invalid escape sequence '\S'
<>:9: SyntaxWarning: invalid escape sequence '\w'
<>:3: SyntaxWarning: invalid escape sequence '\['
<>:5: SyntaxWarning: invalid escape sequence '\S'
<>:9: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_23501/3340264379.py:3: SyntaxWarning: invalid escape sequence '\['
  text = re.sub('\[_*?\]','', text)
/tmp/ipykernel_23501/3340264379.py:5: SyntaxWarning: invalid escape sequence '\S'
  text = re.sub('https?://\S+|www\.\S+','',text)
/tmp/ipykernel_23501/3340264379.py:9: SyntaxWarning: invalid escape sequence '\w'
  text = re.sub('\w*\d\w*','',text)

In [22]:
data['text'] = data['text'].apply(wordopt)

In [23]:
x = data['text']
y= data['class']

In [24]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [26]:
vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

In [30]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(xv_train,y_train)

LogisticRegression()

In [34]:
pred_lr= LR.predict(xv_test)
LR.score(xv_test,y_test)

0.983957219251337

In [35]:
print(classification_report(y_test,pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98      5903
           1       0.98      0.98      0.98      5317

    accuracy                           0.98     11220
   macro avg       0.98      0.98      0.98     11220
weighted avg       0.98      0.98      0.98     11220

In [39]:
print(pred_lr)

[1 1 1 ... 0 0 1]

In [41]:
from sklearn.tree import DecisionTreeClassifier

DT = DecisionTreeClassifier()
DT.fit(xv_train,y_train)
pred_dt= DT.predict(xv_test)
DT.score(xv_test,y_test)

0.9946524064171123

In [42]:
print(classification_report(y_test,pred_dt))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      5903
           1       1.00      0.99      0.99      5317

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

GB = GradientBoostingClassifier(random_state=0)
GB.fit(xv_train,y_train)

In [ ]:
pred_dt= GB.predict(xv_test)
GB.score(xv_test,y_test)

In [ ]:
print(classification_report(y_test,pred_gb))